ModuleRegistrationSystem/urls.py
from django.urls import path
from . import views
from .views import ModuleDetailView, ModuleListView, ModuleCreateView, ModuleUpdateView, ModuleDeleteView
from .views import CourseDetailView
from .views import RegistrationView, ModuleRegistration, ModuleDeregistration
from .views import TeacherListView
from .views import ContactFormView

app_name = 'ModuleRegistrationSystem'

urlpatterns = [

    path('', views.home, name = 'home'),
    path('about', views.about, name='about'),
    path('contact', ContactFormView.as_view(), name='contact'),
    path('teachers', TeacherListView.as_view(), name='teachers'),
    
    path('modules', ModuleListView.as_view(), name='modules'),
    path('module/new', ModuleCreateView.as_view(), name = 'module-create'),
    path('module/<str:pk>', ModuleDetailView.as_view(), name='module-detail'),
    path('module/<str:pk>/update/', ModuleUpdateView.as_view(), name='module-update'),
    path('module/<str:pk>/delete/', ModuleDeleteView.as_view(), name='module-delete'),
    path('course/<str:pk>', CourseDetailView.as_view(), name = 'course-detail'),
    path('registration/<str:username>', RegistrationView.as_view(), name='registrations'),
    path('moduleregistration/<str:pk>', ModuleRegistration, name = 'module-registration'),
    path('modulederegistration/<int:pk>/delete', ModuleDeregistration.as_view(), name = 'module-deregistration')
    

]

api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import CourseViewSet
from rest_framework.authtoken.views import obtain_auth_token

app_name = 'api'
router = DefaultRouter()
router.register('courses', CourseViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('auth', obtain_auth_token, name = 'api_token_auth'),

]

moduleRegistration/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from users.views import ResetPasswordView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ModuleRegistrationSystem.urls')),
    path('api/', include('api.urls')),
    path('register', user_views.register, name = 'register'),
    path('login', auth_views.LoginView.as_view(template_name = 'users/login.html'), name='login'),
    path('logout', auth_views.LogoutView.as_view(template_name = 'users/logout.html'), name='logout'),
    path('studentAccount', user_views.student_account, name = 'studentAccount'),
    path('password-reset/', ResetPasswordView.as_view(), name = 'password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ModuleRegistrationSystem/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse

class Course(models.Model):
    name = models.CharField(max_length = 20, primary_key= 'name')
    startDate = models.DateField(default = timezone.now)
    duration = models.CharField(max_length = 10 ,choices= [('1 year', '1 year'), ('2 years', '2 years'), ('3 years', '3 years')])
    description = models.TextField()

    def __str__(self):
        return f'{self.name}'

class Module(models.Model):
    name = models.CharField(max_length= 40)
    code = models.CharField(max_length= 4, primary_key= 'code')
    credit = models.IntegerField(choices= [(20, 20), (40, 40), (60, 60)])
    category = models.CharField(max_length= 20, choices= [('In-person', 'In person'), ('Online', 'Online')])
    description = models.TextField()
    availability = models.BooleanField(default=True)
    courses_Allowed_To_Register = models.ManyToManyField(Course)

    def __str__(self):
        return f'{self.name}'
    def get_absolute_url(self):
        return reverse('ModuleRegistrationSystem:module-detail', kwargs = {'pk': self.pk})
    
class Registration(models.Model):
    student = models.ForeignKey(User,null = True, related_name= 'studentregistrations', on_delete = models.CASCADE)
    module = models.ForeignKey(Module, null = True, related_name= 'moduleregistrations', on_delete = models.CASCADE)
    dateOfRegistration = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('student', 'module')
        
    def __str__(self):
        return f'{self.student} is registered to {self.module}'
    
    def get_absolute_url(self):
        return reverse('ModuleRegistrationSystem:home')
    
class Teacher(models.Model):
    Name = models.CharField(max_length = 15 ,null = False)
    Email = models.EmailField(null = False)
    Picture = models.ImageField(default = 'default.png', upload_to= 'profile_pics')
    Module = models.ForeignKey(Module, null = True, on_delete = models.DO_NOTHING)

    def __str__(self):
        return f'{self.Name} | {self.Module}'
    

ModuleRegistrationSystem/forms.py
from django import forms
from .models import Registration
from django.core.mail import send_mail




class ModuleReg (forms.ModelForm):
    class Meta:
        model = Registration
        exclude = ['student', 'module']

class ContactForm(forms.Form):
    name = forms.CharField(max_length = 50)
    email = forms.EmailField()
    subject = forms.CharField(max_length = 100)
    enquiry = forms.CharField(widget = forms.Textarea)

    def send_mail(self):
        send_mail(self.cleaned_data.get('subject') + ', sent on behalf of ' + self.cleaned_data.get('name'), self.cleaned_data.get('enquiry'), self.cleaned_data.get('email'), ['C1003593@my.shu.ac.uk'])

ModuleRegistrationSystem/views.py
from typing import Any
from django.db import models
from django.db.models.query import QuerySet
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from .models import Module, Course, Registration, Teacher
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.models import User
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from .forms import ModuleReg, ContactForm
from django.contrib import messages
from django.views.generic.edit import FormView



def home(request):

        course_list = {'courses': Course.objects.all(), 'title': 'Welcome'}
        return render(request, 'ModuleRegistrationSystem/home.html', course_list)

def about(request):

        return render(request, 'ModuleRegistrationSystem/about.html', {'title': 'About us'})

class ContactFormView(FormView):
        form_class = ContactForm
        template_name = 'ModuleRegistrationSystem/contact.html'

        def get_context_data(self, **kwargs: Any):
                context = super(ContactFormView, self).get_context_data(**kwargs)

                context.update({'title': 'Contact Us'})
                return context
        
        def form_valid(self, form):
                form.send_mail()
                messages.success(self.request, 'Successfully sent the enquiry')
                return super().form_valid(form)
        
        def form_invalid(self, form):
                messages.warning(self.request, 'Unable to send the enquiry')
                return super().form_invalid(form)
        
        def get_success_url(self):
                return self.request.path

def modules(request):
        
        module_list = {'modules': Module.objects.all(), 'title': 'List of modules'}
        return render(request, 'ModuleRegistrationSystem/modules.html', module_list)

def registrations(request):
        
        registrations_list = {'registrations': Registration.objects.all(), 'title': 'My Registrations'}
        return render(request, 'ModuleRegistrationSystem/my_registrations.html', registrations_list)

def teachers(request):

        teacher_list = {'teachers': Teacher.objects.all(), 'title': 'List of teachers'}
        return render(request, 'ModuleRegistrationSystem/teachers.html', teacher_list)

class TeacherListView(ListView):
        model = Teacher
        template_name = 'ModuleRegistrationSystem/teachers.html'
        context_object_name = 'teachers'
        ordering = ['Name']
        paginate_by = 3


class ModuleListView(ListView):
        model = Module
        template_name = 'ModuleRegistrationSystem/modules.html'
        context_object_name = 'modules'
        ordering = ['code']
        paginate_by = 3

class RegistrationView(ListView):
        model = Registration
        template_name = 'ModuleRegistrationSystem/my_registrations.html'
        context_object_name = 'registrations'
        paginate_by = 3

        def get_queryset(self):
                user=get_object_or_404(User, username=self.kwargs.get('username'))
                return Registration.objects.filter(student=user).order_by('dateOfRegistration')
        



class ModuleDetailView(DetailView):
        model = Module

class CourseDetailView(DetailView):
        model = Course

class ModuleCreateView(CreateView):
        model = Module
        fields = ['name', 'code', 'credit', 'category', 'description', 'availability', 'courses_Allowed_To_Register']

class ModuleUpdateView(UpdateView):
        model = Module
        fields = ['name', 'code', 'credit', 'category', 'description', 'availability', 'courses_Allowed_To_Register']

class ModuleDeleteView(DeleteView):
        model = Module
        success_url = '/modules'

def ModuleRegistration(request, pk):
        module = get_object_or_404(Module, code=pk)
        if request.method == "POST":
                form = ModuleReg(request.POST)
                if form.is_valid():
                        reg = form.save(commit=False)
                        reg.module = module
                        reg.student = request.user

                        reg.save()
                        messages.success(request, f"You have successfully registered for the module.")
                        return redirect('ModuleRegistrationSystem:modules')
                else:
                        messages.warning(request, f"You are already registered for this module.")
                        print(f"Form Errors: {form.errors}")
        else:
                form = ModuleReg()
        return redirect('ModuleRegistrationSystem:modules')

class ModuleDeregistration(SuccessMessageMixin, DeleteView):
        model = Registration
        success_message = "You have successfully deregistered from the module."

        def get_success_url(self):
                return reverse('ModuleRegistrationSystem:registrations', kwargs={'username': self.request.user.username})


        

ModuleRegistrationSystem/templates/ModuleRegistrationSystem/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}" />
    <title>Sheffield hallam university - {{title}}</title>
</head>

<body>
    <div class="container">
        <header class="site-header">
            <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
                <div class="container">
                <a class="navbar-brand mr-4" href="{% url 'ModuleRegistrationSystem:home' %}">Student registration system</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav mr-auto">
                        <a class="nav-item nav-link" href="{% url 'ModuleRegistrationSystem:home' %}">Home</a>
                        <a class="nav-item nav-link" href="{% url 'ModuleRegistrationSystem:about' %}">About</a>
                        <a class="nav-item nav-link" href="{% url 'ModuleRegistrationSystem:contact' %}">Contact</a>
                        <a class="nav-item nav-link" href="{% url 'ModuleRegistrationSystem:modules' %}">Modules</a>
                        <a class="nav-item nav-link" href="{% url 'ModuleRegistrationSystem:teachers' %}">Teachers</a>
                        {% if user.is_superuser %}
                            <a class="nav-item nav-link" href="{% url 'ModuleRegistrationSystem:module-create' %}">Create new module</a> 
                        {% endif %}
                        {% if user.is_authenticated %}
                            <a class="nav-item nav-link" href="{% url 'ModuleRegistrationSystem:registrations' user.username %}">My registrations</a> 
                        {% endif %}
                    </div>
                    <!-- Navbar Right Side -->
                    <div class="navbar-nav">
                        {% if user.is_authenticated %}
                            <a class="nav-item nav-link" href="{% url 'studentAccount' %}">Student account</a>
                            <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                        {% else %}
                            <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                    <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                        {% endif %}
                    </div>
                </div>
                </div>
            </nav>
        </header>
        <div class="row">
            <div class="col-md-8">
            {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{{message.tags}}">{{ message }}</div>
                {% endfor %}
            {% endif %}

            {% block content %}{% endblock %}
            </div>
        </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>

ModuleRegistrationSystem/templates/ModuleRegistrationSystem/course_detail.html
{% extends "ModuleRegistrationSystem/base.html" %}
{% block content %}
<h1> Information about {{ object }} </h1>
    <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2">Modules on course: 
                {% for module in object.module_set.all %}
                <a class="mr-2" href="{% url 'ModuleRegistrationSystem:module-detail' module.code %}">{{ module.name }}.</a>
                {% endfor %}
                </br>
                <small class="text-muted">{{ object.duration }} long. </small> 
            </div>
        </br>
            <p class="article-content">{{ object.description }}</p></br>
        </div>
    </article>
{% endblock content %}
</body>
</html>

ModuleRegistrationSystem/templates/ModuleRegistrationSystem/home.html
{% extends "ModuleRegistrationSystem/base.html" %}
{% block content %}
    <h1>Welcome to Sheffield Hallam University</h1>
    <div class="article-metadata">
      <h2>Our pages</h2>
        <h3><a class href="{% url 'ModuleRegistrationSystem:modules' %}">Modules</a></h3>
        {% if user.is_authenticated %}
        {% else %}
        <h3><a class href="{% url 'register' %}">Register</a></h3>
        {% endif %}
        <h3><a class href="{% url 'ModuleRegistrationSystem:about' %}">About us</a></h3>
        <h3><a class href="{% url 'ModuleRegistrationSystem:contact' %}">Contact</a></h3>
        <h3><a class href="{% url 'ModuleRegistrationSystem:teachers' %}">List of teachers</a></h3>


    </div>

      <div class="article-metadata">
        <h2>Lorem Ipsum</h2>
        Eos cu dicat nulla vocent. At mei invidunt quaestio, malis civibus ei ius. Quot fastidii nam an. Argumentum disputando mei ea.

        Pri mollis fierent theophrastus an. His eros vituperata quaerendum an. Cum zril propriae dissentiet eu, amet clita ei nam. His dictas patrioque contentiones te, ad animal vituperatoribus vis. Sit ut dolor cetero pericula, quo imperdiet ullamcorper ea. Per etiam choro no, an qui vivendo propriae fabellas. Paulo option duo an, amet liber id qui.

        Mel ad vide homero petentium. Wisi probo verear has ne, no tantas exerci dolore eum. Per honestatis necessitatibus id, qui noluisse probatus ad, an pro quas velit causae. Dicam postulant ea sit. Quas lobortis volutpat et cum, virtute torquatos cu mel, iudico euismod tibique id nam. Eam cu natum libris, et veri mentitum qui.

        Rebum laboramus no mei, his illum vivendo minimum ad. Ea elitr denique omittantur per, dicta dicant tincidunt nam at. Ei pro cibo inermis. Assentior abhorreant no nam. Nemore rationibus eos ad.

        Ad sed quem fastidii officiis, id mea sumo feugait legendos, in odio paulo eirmod sed. Lucilius delicatissimi id vel, movet indoctum in vix. Eam ullum populo insolens ut. Has an populo probatus dignissim, an velit mediocritatem eam.

      </div>
      
      <div class="article-metadata">
        <h2>Lorem Ipsum</h2>
        Laoreet accusam ut sed, vis mundi quaestio definitionem ea, qui audire labitur numquam ne. Pri ex graecis minimum, ei vide nonumes qui, eum amet aeque ut. Te mei illum fastidii, epicuri imperdiet quo te, decore vidisse conceptam an ius. Ex alia dicat reprehendunt vel, in alii dicam quo, mea no detracto appetere dissentiunt. Soluta vituperatoribus et pri, id ius adhuc scripta, no eius simul legere vis. An sed dicam blandit suscipiantur, ne diceret appareat indoctum vix.

        Enim recteque eu sea. Pro equidem inimicus neglegentur ne, equidem oporteat laboramus ea his, agam deserunt intellegebat ea duo. Melius cetero veritus sed cu. Ius stet eros vivendum ei, augue inciderint voluptatibus in pro. Pro ad veniam detracto, ad qui amet imperdiet repudiare. Mea accumsan scaevola accusata an. Eleifend dignissim ut per, te idque graecis maiestatis cum.

        Atqui praesent quaerendum mea ex, eum primis consulatu ne, paulo dolore maluisset ex vis. Omnium fabulas pri ex. Id quo omnis fuisset electram, ad eam dico elit. Saepe fabellas similique duo ne, quodsi nominati ei pri, no brute bonorum epicurei nam. Sea purto latine te, persecuti democritum et pro.

        Duo quidam cetero ex, ut alia expetendis vel. Mel falli omittam assentior in, propriae vulputate eum an, eam ex iisque verterem menandri. Mei ut debet propriae imperdiet, homero possim consetetur sea id, odio argumentum te nam. Paulo fuisset inciderint vix ei, tempor putent te vix.

      </div>
 
    <div class="col-md-4">
            <h2>Courses</h2>
            <p class='text-muted'>A list of courses offered by us.
                {% for course in courses %} 
                  <div class="article-metadata">
                    <h3><a class href="{% url 'ModuleRegistrationSystem:course-detail' course.name %}">
                    {{ course.name }}</a></h3>
                    </br>
                  </div>
                {% endfor %}
            </p>
    </div>
{% endblock content %}
</body>
</html>

ModuleRegistrationSystem/templates/ModuleRegistrationSystem/module_detail.html
{% extends "ModuleRegistrationSystem/base.html" %}
{% load crispy_forms_tags %}
{% load custom_filters %}
{% block content %}
    <h1>Information about {{ object }} </h1>
    <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2">Courses allowed to register: {% for courses_Allowed_To_Register in object.courses_Allowed_To_Register.all %} <a class="mr-2" href="{% url 'ModuleRegistrationSystem:course-detail' courses_Allowed_To_Register.name %}"> {{ courses_Allowed_To_Register }}. </a>
                    {% endfor %}</a>
                </br>
                <small class="text-muted">{{ object.credit }} credits offered. Module Code: {{ object.code }}</small> 
            </div>
        </br>
            <p class="article-content">{{ object.description }}</p></br>
            <p class="article-content">In person or online: {{ object.category }}</p></br>
            {% if object.availability == True %}
                <p class="article-content">Module available at the moment: Yes</p>
            {% else %}
                <p class="article-content">Module available at the moment: No</p>
            {% endif %}
            <div class="article-metadata">
            </div>
            <a class="mr-2">Students registered to module: </a>
            {% for registration in module.moduleregistrations.all %}
                <div>
                    <a class="mr-2" >{{ registration.student }}</a>
                    <img class="rounded-circle article-img" src="{{ registration.student.studentaccount.image.url }}"/>
                    <a class="mr-2"></a>
                </div>
                {% empty %}
                    <a class="mr-2">No students are registered to this module.</a>
            {% endfor %}
            </br>
            <div class="article-metadata">
            </div>
        </br>

        {% if user.is_authenticated %}

                {% if user.studentaccount.Course in module.courses_Allowed_To_Register.all %}

                    {% if user|if_registered:module %}

                        <a class="mr-2">You are already registered for this module, view registrations here: </a>
                        <a class="ml-2" href="{% url 'ModuleRegistrationSystem:registrations' user.username %}">my registrations</a>

                    {% else %}
                    
                        {% if module.availability == True %}
                            <form method="POST" action="{% url 'ModuleRegistrationSystem:module-registration' module.code %}">
                                {% csrf_token %}
                                {{ form | crispy }}
                                <button class="btn btn-success" type="submit">Register Now</button>
                            </form>

                        {% elif module.availability == False %}
                            <a class="mr-2">This module is not currently available.</a>
                        {% endif %}
                    {% endif %}
                {% else %}
                    <a class="mr-2">Your course is not eligible to enrol to this module.</a>
                {% endif %}
            {% else %}
                <a class="mr-2">You are not logged in, you must login to register for a module.</a>
                <a class="ml-2" href="{% url 'login' %}">Login</a>
            {% endif %}
            {% if user.is_superuser %}
                <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'ModuleRegistrationSystem:module-update' object.code %}">Update</a>
                <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'ModuleRegistrationSystem:module-delete' object.code %}">Delete</a>
            {% endif %}
        </div>
    </article>

{% endblock content %}
</body>
</html>

ModuleRegistrationSystem/templates/ModuleRegistrationSystem/modules.html
{% extends "ModuleRegistrationSystem/base.html" %}
{% load custom_filters %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>The modules we offer:</h1>
{% for module in modules %}
    <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2">Courses allowed to register: {% for courses_Allowed_To_Register in module.courses_Allowed_To_Register.all %} <a class="mr-2" href="{% url 'ModuleRegistrationSystem:course-detail' courses_Allowed_To_Register.name %}"> {{ courses_Allowed_To_Register }}. </a>
                    {% endfor %}</a>
                </br>
                <small class="text-muted">{{ module.credit }} credits offered. Module Code: {{ module.code }}</small> 
            </div>
            <h2><a class="article-title" href="{% url 'ModuleRegistrationSystem:module-detail' module.code %}">{{ module }}</a></h2>
            <p class="article-content">{{ module.description }}</p>
            <div class="article-metadata"></div>

            {% if user.is_authenticated %}

                {% if user.studentaccount.Course in module.courses_Allowed_To_Register.all %}

                    {% if user|if_registered:module %}

                        <a class="mr-2">You are already registered for this module, view registrations here: </a>
                        <a class="ml-2" href="{% url 'ModuleRegistrationSystem:registrations' user.username %}">my registrations</a>

                    {% else %}
                    
                        {% if module.availability == True %}
                            <form method="POST" action="{% url 'ModuleRegistrationSystem:module-registration' module.code %}">
                                {% csrf_token %}
                                {{ form | crispy }}
                                <button class="btn btn-success" type="submit">Register Now</button>
                            </form>

                        {% elif module.availability == False %}
                            <a class="mr-2">This module is not currently available.</a>
                        {% endif %}
                    {% endif %}
                {% else %}
                    <a class="mr-2">Your course is not eligible to enrol to this module.</a>
                {% endif %}
            {% else %}
                <a class="mr-2">You are not logged in, you must login to register for a module.</a>
                <a class="ml-2" href="{% url 'login' %}">Login</a>
            {% endif %}

    </article>
{% endfor %}

{% if is_paginated %}
{% if page_obj.has_previous %}
<a class="btn btn-outline-info mb-4" href="?page=1">First</a>
<a class="btn btn-outline-info mb-4" href="?page={{page_obj.previous_page_number}}">Previous</a>
{% endif %}
{% for num in page_obj.paginator.page_range %}
{% if page_obj.number == num %}
<a class="btn btn-info mb-4" href="?page={{num}}">{{num}}</a>
{% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
<a class="btn btn-outline-info mb-4" href="?page={{num}}">{{num}}</a>
{% endif %}
{% endfor %}
{% if page_obj.has_next %}
<a class="btn btn-outline-info mb-4" href="?page={{page_obj.next_page_number}}">Next</a>
<a class="btn btn-outline-info mb-4" href="?page={{page_obj.paginator.num_pages}}">Last</a>
{% endif %}
{% endif %}

{% endblock content %}
</body>
</html>

ModuleRegistrationSystem/templates/ModuleRegistrationSystem/my_registrations.html
{% extends "ModuleRegistrationSystem/base.html" %}
{% block content %}
    <h1>My registrations</h1>
    {% for registration in registrations %}
        <article class="media content-section">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2">Date registered: {{ registration.dateOfRegistration }} </a> 
                    </br>
                    <small class="text-muted"></small> 
                </div>
                <h2><a class="article-title">{{ registration.module }}</a></h2>
                <p class="article-content"></p>
                <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'ModuleRegistrationSystem:module-deregistration' registration.id %}">Deregister</a>
            </div>
        </article>
    {% empty %}
        <article class="media content-section">
            <div class="media-body">
                <div class="article-metadata">
                    <h2><a class="article-title">No modules found.</a></h2>
                    <small class="text-muted"></small> 
                </div>
                    <a class="mr-2">You appear to have no registrations, here is a link to the modules page</a> 
            </br>
                    <a class="btn btn-info btn-sm mt-1 mb-1" href="{% url 'ModuleRegistrationSystem:modules' %}">List of modules</a>
            </div>
        </article>
    {% endfor %}
{% if is_paginated %}
{% if page_obj.has_previous %}
<a class="btn btn-outline-info mb-4" href="?page=1">First</a>
<a class="btn btn-outline-info mb-4" href="?page={{page_obj.previous_page_number}}">Previous</a>
{% endif %}
{% for num in page_obj.paginator.page_range %}
{% if page_obj.number == num %}
<a class="btn btn-info mb-4" href="?page={{num}}">{{num}}</a>
{% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
<a class="btn btn-outline-info mb-4" href="?page={{num}}">{{num}}</a>
{% endif %}
{% endfor %}
{% if page_obj.has_next %}
<a class="btn btn-outline-info mb-4" href="?page={{page_obj.next_page_number}}">Next</a>
<a class="btn btn-outline-info mb-4" href="?page={{page_obj.paginator.num_pages}}">Last</a>
{% endif %}
{% endif %}
{% endblock content %}
</body>
</html>